### ISSUE TITLE
'--verbose' option doesn't seem to work.

### ISSUE THREAD

**Issue by tillea** [tjko/jpeginfo#10]
Hi,
I'm forwarding [another bug report against the Debian package of jpeginfo](https://bugs.debian.org/308294) which claims that the `-v, --verbose` option has no visible effect.  It raises the question: _Perhaps the '-v' switch only applies to certain options?  If
so, the man page doesn't mention which options._
Kind regards, Andreas.

**Comment by tjko** [comment]
Thanks, seems like it wasn't really doing much.  On latest 1.7.0 it should now work and enable verbose (debug) output showing more details about what is happening.
