### ISSUE TITLE
Shorthand json option -j does not work

### ISSUE THREAD

**Issue by FredTreg** [tjko/jpeginfo#18]
`jpeginfo -h` indicates that the option `-j` can be used as an equivalent for `--json` but this does not seem to be the case.

```
jpeginfo -j great.jpg 
jpeginfo: invalid option -- 'j'
```

Version: 1.7.0

**Comment by tjko** [comment]
Thanks for pointing this out.  This should now be fixed via 2efede89701b99bb94d834433e8c8613412d288f
