### ISSUE TITLE
Install on Synology DS212 (arm processor)

### ISSUE THREAD

**Issue by l2** [tjko/jpeginfo#2]
I tried to compile jpeginfo on Synology server (DS212 with arm processor). I can compile it normally but I can't execute it. I have this error: 
`Wrong JPEG library version: library is 80, caller expects 62`

ldd says:
> libjpeg.so.62 => /lib/libjpeg.so.62 (0x40031000)
> libc.so.6 => /lib/libc.so.6 (0x40085000)
> libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x401c7000)
> /lib/ld-linux.so.3 (0x40000000)

This is really weird because the arm package for debian (https://packages.debian.org/wheezy/jpeginfo) works fine.

**Comment by szepeviktor** [comment]
What is your vesion of libjpeg-dev?

**Comment by szepeviktor** [comment]
https://github.com/tjko/jpeginfo/blob/master/README#L5-L7

**Comment by l2** [comment]
I don't really know but on my `/lib` directory, I have:
``
lrwxrwxrwx  1 root root      16 2014-12-29 16:21 libjpeg.so -> libjpeg.so.8.0.2
lrwxrwxrwx  1 root root      16 2014-12-29 16:21 libjpeg.so.62 -> libjpeg.so.8.0.2
lrwxrwxrwx  1 root root      16 2014-12-29 16:21 libjpeg.so.8 -> libjpeg.so.8.0.2
-rwxr-xr-x  1 root root  212812 2014-12-03 01:42 libjpeg.so.8.0.2
lrwxrwxrwx  1 root root      21 2014-12-29 16:21 libturbojpeg.so -> libturbojpeg.so.0.0.0
lrwxrwxrwx  1 root root      21 2014-12-29 16:21 libturbojpeg.so.0 -> libturbojpeg.so.0.0.0
-rwxr-xr-x  1 root root  232440 2014-12-03 01:42 libturbojpeg.so.0.0.0``

**Comment by szepeviktor** [comment]
`libjpeg.so.62 -> libjpeg.so.8.0.2` This could be the problem.
Please change the symlink to 6.2.

**Comment by szepeviktor** [comment]
...or try to remove it.

**Comment by l2** [comment]
I didn't have any package manager. I remove the `libjpeg.so.62` link but `jpeginfo` says: 
`./jpeginfo: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory`. But I created new symlink using `libjpeg.so.62` available in an other directory (`/opt/lib/libjpeg.so.62`). Now, `jpeginfo` works fine.

I am very suprised because with the package for debian version `1.6.0-5`, it works fine... 

Thank you for your help.

**Comment by szepeviktor** [comment]
Please use only one version on libjpeg.

**Comment by szepeviktor** [comment]
Close this issue!
