### ISSUE TITLE
Compile under Windows / Cygwin

### ISSUE THREAD

**Issue by arm-in** [tjko/jpeginfo#6]
Unpacking the source code under Windows is not possible, since the folder name "AUX" is a reserved keyword.
https://cygwin.com/cygwin-ug-net/using-specialnames.html

In the following, compiling is also not possible.

**Comment by tjko** [comment]
Thanks, this should now work?  Directory aux/ has now been renamed to tools/

**Comment by arm-in** [comment]
Looks much better now with 7ed000d21c1137805e8e4cc5df6bf1f058a87073. I can confirm that unpacking on Windows completes successfully without error.

**Comment by poisonborz** [comment]
@arm-in could you please provide some instructions on how to compile/run under Cygwin? This issue is a top hit on google for running jpeginfo on windows/cygwin.
