### ISSUE TITLE
Win32 support

### ISSUE THREAD

**Issue by tumagonx** [tjko/jpeginfo#7]
I have compiled native jpeginfo using mingw32, it works great you just need to change "open" mode from "r" into "rb" in jpeginfo.c which needed for "newline" workaround and IIRC harmless for *nix. Regarding illegal name "aux" name I would suggest you rename it to something else, though it should be okay on MSys/Cygwin as long as the archive decompressed using posix tar/unzip since they use NTAPI instead of Win32API.

**Comment by tumagonx** [comment]
BTW I found `-d` option isn't working in Windows because filehandle hasn't closed yet around `jpenginfo.c:381`  (not sure how this works in linux)

**Comment by tjko** [comment]
> I have compiled native jpeginfo using mingw32, it works great you just need to change "open" mode from "r" into "rb" in jpeginfo.c which needed for "newline" workaround and IIRC harmless for *nix. Regarding illegal name "aux" name I would suggest you rename it to something else, though it should be okay on MSys/Cygwin as long as the archive decompressed using posix tar/unzip since they use NTAPI instead of Win32API.

Thanks, I changed the fopen() call and renamed aux/ to tools/.  Does it now work as expected?

**Comment by tumagonx** [comment]
yes that's works, how about the fclose in jpenginfo.c:381 to fix `-d` option in Windows?

**Comment by tjko** [comment]
I had missed that, it should now work?

**Comment by tumagonx** [comment]
okay thanks.
