### ISSUE TITLE
A SIGKILL occurs while reading a JPEG file having a huge size of the pixel

### ISSUE THREAD

**Issue by tank0123** [tjko/jpeginfo#8]
## **System Configuration**
- jpeginfo version: v1.6.2beta
- libjpeg-dev version : 8c-2ubuntu8
- Used arguments: -c
- Environment (Operating system, version and so on): Ubuntu 18.04.2 64bit

A SIGKILL interrupt occurs while reading the jpeg file. 
It causes while executing on the jpeg_start_decompress function of jpeginfo.c (364 line).

### **Printed messages:**
Starting program: /home/server/analysis/jpeginfo/jpeginfo -c /home/server/jpeginfo_PoC
Program terminated with signal SIGKILL, Killed.

This bug occurs when the libjpeg is processing image with abnormally large pixels.
(This is similar to a bug that occurred with the jpegoptim. [https://github.com/tjko/jpegoptim/issues/81](https://github.com/tjko/jpegoptim/issues/81))

It was not possible to obtain stack trace because the OS forcibly kills the process due to excessive memory allocation.
It seems to occur while libjpeg is processing an abnormal jpeg file. 

Therefore, for images with abnormally large pixels, error handling logic seems to be needed.

I've attached the file. Please download and check the file.
[jpeginfo_PoC.zip](https://github.com/tjko/jpeginfo/files/6998508/jpeginfo_PoC.zip)

**Comment by tjko** [comment]
Unable to reproduce the issue:

```
$ ./jpeginfo -c jpeginfo_PoC
jpeginfo_PoC 65280 x 65280 24bit JFIF  P    9871  Insufficient memory (case 11)  [ERROR]
```
