### ISSUE TITLE
Man page is incomplete

### ISSUE THREAD

**Issue by tillea** [tjko/jpeginfo#9]
Hi,
I'm just forwarding an [issue reported against the Debian package](https://bugs.debian.org/260337):
 
_The next-to-last column of the output is undocumented and obscure. Actually, the man page should list what all the columns are,
but most of the others are fairly easy to figure out.

On the images I tried, I just got 'N' in that column._

I just verified that this issue persists also for the now uploaded version 1.6.1.

Kind regards, Andreas.

PS: It would be great if you could tag releases here on Github.

**Comment by tjko** [comment]
Thanks.  Man page has now been updated: 20f602152b12592600e196cfbaec55ab5e377c61
